# -*- coding: utf-8 -*-
"""real-estate_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLU64bUxinU-PU_ymwTLGDz2uueT58nT
"""

import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import warnings

warnings.filterwarnings("ignore")

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Real Estate EDA Dashboard",
    layout="wide"
)

st.title("Real Estate Exploratory Data Analysis")

# Avoid Altair row warnings
alt.data_transformers.disable_max_rows()

# ---------------- LOAD DATA ----------------
DATA_PATH = "india_housing_prices.csv.gz"

@st.cache_data
def load_data(path):
    return pd.read_csv(path)

df = load_data(DATA_PATH)

# ---------------- SAMPLE DATA FOR VISUALS ----------------
@st.cache_data
def sample_data(df, n=50000):
    return df.sample(n, random_state=42)

df_viz = sample_data(df)

# ---------------- DATA CLEANING ----------------
for col in df.select_dtypes(include="object"):
    df[col] = df[col].astype(str).str.strip().replace("nan", np.nan)

numeric_cols = [
    "BHK", "Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt",
    "Year_Built", "Floor_No", "Total_Floors",
    "Age_of_Property", "Nearby_Schools", "Nearby_Hospitals",
    "Public_Transport_Accessibility", "Parking_Space"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# ---------------- FEATURE ENGINEERING ----------------
if {"Price_in_Lakhs", "Size_in_SqFt"}.issubset(df.columns):
    df["Price_Rs"] = df["Price_in_Lakhs"] * 100000
    df["Price_per_SqFt"] = df["Price_Rs"] / df["Size_in_SqFt"]

CURRENT_YEAR = 2025
if "Year_Built" in df.columns:
    df["Age_of_Property"] = df["Age_of_Property"].fillna(
        CURRENT_YEAR - df["Year_Built"]
    )

# ---------------- HANDLE MISSING VALUES ----------------
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include="object"):
    df[col] = df[col].fillna("Unknown")

df.drop_duplicates(inplace=True)

# ---------------- SUMMARY ----------------
st.subheader("Statistical Summary")
st.dataframe(df.describe(), use_container_width=True)

# ================= UNIVARIATE ANALYSIS =================
st.header("Univariate Analysis")

def histogram(data, column, title):
    """
    Memory-safe histogram with correct Altair schema
    """
    return (
        alt.Chart(data)
        .transform_bin(
            "bin",
            column,
            bin=alt.Bin(maxbins=30)
        )
        .transform_aggregate(
            count="count()",
            groupby=["bin"]
        )
        .mark_bar()
        .encode(
            x=alt.X("bin:Q", title=column),
            y=alt.Y("count:Q", title="Count"),
            tooltip=["count:Q"]
        )
        .properties(title=title)
    )

st.altair_chart(
    histogram(df_viz, "Price_in_Lakhs", "Price Distribution (Lakhs)"),
    use_container_width=True
)

st.altair_chart(
    histogram(df_viz, "Size_in_SqFt", "Size Distribution (SqFt)"),
    use_container_width=True
)

st.altair_chart(
    histogram(df_viz, "Price_per_SqFt", "Price per SqFt Distribution"),
    use_container_width=True
)

# ================= BIVARIATE ANALYSIS =================
st.header("Bivariate Analysis")

scatter = (
    alt.Chart(df_viz)
    .mark_circle(size=40, opacity=0.4)
    .encode(
        x=alt.X("Size_in_SqFt:Q", title="Size (SqFt)"),
        y=alt.Y("Price_in_Lakhs:Q", title="Price (Lakhs)"),
        tooltip=[
            alt.Tooltip("Size_in_SqFt:Q", format=","),
            alt.Tooltip("Price_in_Lakhs:Q", format=","),
            alt.Tooltip("City:N")
        ]
    )
    .properties(title="Size vs Price")
)

st.altair_chart(scatter, use_container_width=True)

# ================= CITY ANALYSIS =================
if "City" in df.columns:
    city_avg = (
        df.groupby("City", as_index=False)["Price_in_Lakhs"]
        .mean()
        .sort_values("Price_in_Lakhs", ascending=False)
        .head(10)
    )

    city_bar = (
        alt.Chart(city_avg)
        .mark_bar()
        .encode(
            x=alt.X("City:N", sort="-y"),
            y=alt.Y("Price_in_Lakhs:Q"),
            tooltip=["City:N", "Price_in_Lakhs:Q"]
        )
        .properties(title="Top 10 Cities by Average Price")
    )

    st.altair_chart(city_bar, use_container_width=True)

# ================= PROPERTY TYPE =================
if "Property_Type" in df.columns:
    box = (
        alt.Chart(df_viz)
        .mark_boxplot()
        .encode(
            x=alt.X("Property_Type:N", title="Property Type"),
            y=alt.Y("Price_per_SqFt:Q", title="Price per SqFt"),
            tooltip=["Property_Type:N"]
        )
        .properties(title="Price per SqFt by Property Type")
    )

    st.altair_chart(box, use_container_width=True)

# ================= CORRELATION (REDUCED & SAFE) =================
st.header("Correlation Heatmap")

corr_cols = [
    "Price_in_Lakhs",
    "Size_in_SqFt",
    "BHK",
    "Price_per_SqFt",
    "Age_of_Property"
]

corr_df = df[corr_cols].corr().stack().reset_index()
corr_df.columns = ["Feature X", "Feature Y", "Correlation"]

heatmap = (
    alt.Chart(corr_df)
    .mark_rect()
    .encode(
        x="Feature X:N",
        y="Feature Y:N",
        color=alt.Color(
            "Correlation:Q",
            scale=alt.Scale(scheme="redblue")
        ),
        tooltip=["Feature X:N", "Feature Y:N", "Correlation:Q"]
    )
)

st.altair_chart(heatmap, use_container_width=True)

# ================= LOCALITY =================
if "Locality" in df.columns:
    top_local = (
        df.groupby("Locality", as_index=False)["Price_per_SqFt"]
        .mean()
        .sort_values("Price_per_SqFt", ascending=False)
        .head(10)
    )

    local_bar = (
        alt.Chart(top_local)
        .mark_bar()
        .encode(
            x=alt.X("Locality:N", sort="-y"),
            y=alt.Y("Price_per_SqFt:Q"),
            tooltip=["Locality:N", "Price_per_SqFt:Q"]
        )
        .properties(title="Top 10 Expensive Localities")
    )

    st.altair_chart(local_bar, use_container_width=True)

# ---------------- DONE ----------------
st.success("EDA Completed Successfully")